# NOTICE: you must have an .env file (see the .env.template as a reference).
version: '2'

services:
  db:
    #https://hub.docker.com/_/rethinkdb/
    image: rethinkdb:2.3
  web:
    build: .
    container_name: example-flask-todo
    # all env items should be in .env
    env_file: .env
    # start the app in 'setup' mode (to create the db)
    command: /entrypoint.sh -s
    # start the app in 'debug' (using internal flask server) mode.
    #command: /entrypoint.sh -d
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    depends_on:
    # wait for db to be started.
    - db
